apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: front-obligatorio-tecredsw
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: desmoris/apache-obligatorio-tecredsw-2025
          ports:
            - containerPort: 80
          env:
            - name: REPO_URL
              value: "https://github.com/DamianEsmoris/obligatorio-tecredsw-2025_frontend"
